### ISSUE TITLE
support for HC837 005010X223A2

### ISSUE THREAD

**Issue by pradoshac** [kputnam/stupidedi#100]
I need to generate an  HC837 005010X223A2 file by using stupidedi. Is it supported or not?` 
The first 3 segments of my file is below..my complete file is also attached here..please check
https://github.com/kputnam/stupidedi/files/587134/MYFILE.txt

ISA*00*          *00*          *ZZ*770431902      *ZZ*263086998      *160227*1042*^*00501*000000072*0*T*:~
GS*HC*770431902*263086998*20160227*1042*0072*X*005010X223A2~
ST*837*0001*005010X223A2~
BHT*0019*00*0072*20160227*1042*CH~
 
How can i  generate these type of files by using stupidedi. I need your help .is there any way? please advice

Thanks,
Prado

**Comment by kputnam** [comment]
No, the grammar for institutional claims (837I) is not included (only professional claims, 837P). If you have the documentation from X12.org you can transcribe the grammar as described in `doc/Transcribing.md` and following the other HIPAA examples that are included.

**Comment by kputnam** [comment]
You might want to contact @pepito2k about collaborating, he might be working on this (see #86)

**Comment by pradoshac** [comment]
Hi sir,i  contacted pepito2k and asked about the issue .He told me that i needed to fork the gem and write the parser to make it work.Unfortunately he can't share the code of the parser because it was made for his client and he wasn't given permission to share the code with the community .
So can you please describe the process of forking the gem and parser writing? including the details of files that i need to modify,what are changes needed for those  files for supporting 837 institutional files.

If it possible can u please add the support for generating 837 institutional files.I can give you my sample files for you, then it will be a great help for us.
Do you know any other way or gems for generating  HC837 institutional files  in ruby ? 

Thanks,

PRADO

**Comment by kputnam** [comment]
Unfortunately I don't have the time to make those changes (it's not an easy effort, and 837I is one of the most complicated ones). If you have the official documentation you can follow `doc/Transcribing.md` and review the previous pull requests where people have contributed other grammars (eg, #98, #84, #60, #34, #27, etc).

There are other X12 EDI ruby libraries, but I don't have experience with them. From what I remember of six years ago, I think many of them didn't require predefined grammars, so you could get started more easily (but as a consequence, they didn't offer much in the way of validation).

**Comment by pepito2k** [comment]
My client gave me permission to share the code for the 837i parser, check PR #101

**Comment by pradoshac** [comment]
Thank you sir .it will be very helpful for me.Actually i was stuck with that .once again thank you..
