### ISSUE TITLE
Ruby 2.4.0 support -  One spec failure

### ISSUE THREAD

**Issue by irobayna** [kputnam/stupidedi#102]
The following spec does not pass with Ruby 2.4.0
```ruby
  property("calls n-ary methods") do
    map(between(0, 10)) { integer }
  end.check do |as|
    :call.to_proc.call(lambda{|*bs| bs.length }, *as).should == as.length
  end
```
I believe it might be due to the new changes in regard to the [hash table improvement](https://bugs.ruby-lang.org/issues/12142) 

Do you think it will be safe to skip this one moving forward?

**Comment by irobayna** [comment]
@kputnam Are you ok if I comment out the spec mentioned above so all specs run correctly under ruby 2.4 ?

**Comment by kputnam** [comment]
Sorry I haven't looked at this yet. I'm pretty nervous about it, since it used to be very important -- that behavior might not be required anymore though. I'll look into it more closely this weekend.

**Comment by irobayna** [comment]
@kputnam Any updates on this one?

**Comment by irobayna** [comment]
@kputnam  did you find time to look at this item?

**Comment by jakeonfire** [comment]
@irobayna there are more issues than that with ruby 2.4.1
 - a warning about constants being defined within a refinement scope
 - `rake` is no longer part of ruby stdlib but it's required in `stupidedi.gemspec`

**Comment by irobayna** [comment]
@jakeonfire Thanks for the heads up.   I see you made a few changes to support ruby 2.4.1 
Could you send a PR?
