### ISSUE TITLE
Stupidedi::Exceptions::ParseError

### ISSUE THREAD

**Issue by pradoshac** [kputnam/stupidedi#105]
Iam generating an hc837 file by using stupid edi  (VERSION = "1.2.12")
evrYthing is okay but while  generating the H1 segment by composite  i got some error 

error:-Stupidedi::Exceptions::ParseError iGenerate837
value ABF not allowed in element HI01-03

Below is my generator code:-
       b.HI b.composite('ABK', dxcode)
        b.HI b.composite('APR', dxcode)
        b.HI b.composite('ABF',dxcode2,'ABF',dxcode3,'ABF',dxcode4)
I got the error related to the third H1 segment.It didn't support the value 'ABF' in HI01-03 postion.
why this happens? where i need to modify the code for accepting those values..please help

**Comment by kputnam** [comment]
Sorry this took a while to track down. Looking at the official specification for 837I, that segment, `OTHER DIAGNOSIS INFORMATION` is encoded correctly: [here](https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/guides/005010/X223-HC837I.rb#L420).

The error message is correct. I think what you intended to do is this:

```ruby
b.HI b.composite('ABK', dxcode)
b.HI b.composite('APR', dxcode)
b.HI b.composite('ABF',dxcode2), b.composite('ABF',dxcode3), b.composite('ABF',dxcode4)
```

The difference is you have constructed one large composite element in `HI01` with six elements. The first two are fine, but the rest belong in separate composite elements, `HI02` and `HI03`. Does that make sense?

**Comment by irobayna** [comment]
@pradoshac closing this item
