### ISSUE TITLE
Does it provide support for 810/850/864/856?

### ISSUE THREAD

**Issue by ketan-fab** [kputnam/stupidedi#111]
Does this tool provide support for 810/850/864/856? If yes can I see the examples for parsing and creating those?

**Comment by awwaiid** [comment]
@ketan-fab check out https://github.com/kputnam/stupidedi/tree/master/lib/stupidedi/contrib which has some examples of these. I don't see any instructions, but looks like you can even use these off-the-shelf.

**Comment by irobayna** [comment]
@ketan-fab yes some are supported - 856, 850

you can see all supported transactions here:

https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/config.rb

810 and 864 are not supported but you are welcome to add support, if you like
