### ISSUE TITLE
API Documentation link broken

### ISSUE THREAD

**Issue by kmeyerhofer** [kputnam/stupidedi#221]
When visiting the [API Documentation](http://rubydoc.info/github/irobayna/stupidedi/master/frames) link in the README.md, an error is shown stating the documentation page couldn't be found (screenshot below).

![Screenshot from 2020-06-04 13-20-54](https://user-images.githubusercontent.com/24800059/83801522-85ce8280-a666-11ea-8a27-fcbc9762a3e1.png)

The [previous link](https://rubydoc.info/github/kputnam/stupidedi/master) still works from the [changes made in this commit](https://github.com/irobayna/stupidedi/commit/263daeaf68982479a0af9f9be2a643abe14332b8#diff-04c6e90faac2675aa89e2176d2eec7d8L9).

**Comment by kputnam** [comment]
Thanks for pointing this out. I think it should be fixed, now that rubydoc.info is aware of this repo. Can you confirm it works now?

**Comment by kputnam** [comment]
I notice [the new doc address](https://rubydoc.info/github/irobayna/stupidedi/master) has a bunch of things missing from the class list. I think I've had this issue before on local documentation builds and narrowed it down to a particular commit in yard. I'll check into this as time permits, but maybe for now it's easier to just change the link to point to the old address.

**Comment by kmeyerhofer** [comment]
Yes, the link does work now, but like you said it is missing a lot of documentation.

Thanks for looking into it.
