### ISSUE TITLE
Parsing an 837 and grabbing segment values

### ISSUE THREAD

**Issue by chasestory** [kputnam/stupidedi#253]
Hello, I am having some confusion with understanding how to grab values at specific segments, when I look at the navigation.md I see that I can find each segment, and then get the element of segment like this: 
```
x = parser.first.
  flatmap{|x| x.find(:GS)  }.
  flatmap{|x| x.find(:ST)  }.
  flatmap{|x| x.find(:HL, nil, nil, "20") }.
  flatmap{|x| x.find(:NM1)          }.
  flatmap{|x| x.find(:N3)          }.
  flatmap{|x| x.element(1) }.
  map(&:node)
```

But the result I get is
```
Either.success(AN.value[ E166: Billing Provider Address Line](111 billing provider address))
```
is it possible to just grab the value response, that is within the success wrapper? 

the end goal is to eventually parse 837s and generate 835s in response... and as far as I can tell this is the best way to get values?
Please help! :)

**Comment by kmeyerhofer** [comment]
https://github.com/kputnam/stupidedi/blob/9e1b9896b371078d439e72505165082b898cd00a/README.md#reading-traversing

@chasestory Did you see this section of the README?

This in particular:

```ruby
# ...

# Helper function: fetch an element from the current segment
def el(m, *ns, &block)
  if Stupidedi::Either === m
    m.tap{|m| el(m, *ns, &block) }
  else
    yield(*ns.map{|n| m.elementn(n).map(&:value).fetch })
  end
end

# Print some information
parser.first
  .flatmap{|m| m.find(:GS) }
  .flatmap{|m| m.find(:ST) }
  .tap do |m|
    el(m.find(:N1, "PR"), 2){|e| puts "Payer: #{e}" } # MY COMMENT HERE - This is where you can get the value
    el(m.find(:N1, "PE"), 2){|e| puts "Payee: #{e}" } # MY COMMENT HERE - This is where you can get the value
  end
  .flatmap{|m| m.find(:LX) }
  .flatmap{|m| m.find(:CLP) }
  .flatmap{|m| m.find(:NM1, "QC") }
  .tap{|m| el(m, 3, 4){|l,f| puts "Patient: #{l}, #{f}" }}

# ...
```

**Comment by chasestory** [comment]
Ahh yes thank you for responding, I totally forgot that I figured it out after I wrote this!
