### ISSUE TITLE
Is there a way to skip validations and build without some of the segments

### ISSUE THREAD

**Issue by Tejareddy94** [kputnam/stupidedi#254]
Hi can anyone please help me to skip validations or segments

    config = Stupidedi::Config.hipaa
    b = Stupidedi::Parser::BuilderDsl.build(config)

      b.NM1 "85", "2", "PROVIDER BILLING", nil, nil, nil, nil, "XX", "323234"

I want to skip this segment and proceed with Generation. i know this is like stupid to ask but my team wants to generate without this segment

**Comment by kputnam** [comment]
Hi Teja,

You can try passing `false` as the second argument to BuilderDsl.new:

```ruby
config = ...
b = Stupidedi::Builder::BuilderDsl.build(config, false)
```

This turns of "strict" validation. I can't say for sure the differences between strict and non-strict validation, since I've not worked on this project for a while.

**Comment by Tejareddy94** [comment]
Okay Thank You will try that @kputnam
