### ISSUE TITLE
value 091 is not allowed in element DTM01 Date/Time Qualifier

### ISSUE THREAD

**Issue by vsrboth** [kputnam/stupidedi#257]
From the 820 documents of CRA, it said that DTM01 accepts '091', however, using the gem to generate DTM, it keeps saying not allowed.

does anyone come across this error? I am trying to look for a list of available values. Still no luck. 
Appreciate if anyone can help out. Thanks

**Comment by kputnam** [comment]
Hi and thanks for the bug report. Could you provide some steps to reproduce this? You can find the list of allowed values in one of two places: the transaction set definition (see [lib/stupidedi/transaction_sets](https://github.com/kputnam/stupidedi/tree/master/lib/stupidedi/transaction_sets)).

Based on the 820 transaction sets we have wired up [here](https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/config.rb#L68), you must be using either X12 version 003010 or 005010. Both of those show we only have the "standard" definition, not the "implementation" which has more details and is a subset of the standard. That means you can find the allowed values by looking of the segment [definition for DTM](https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/versions/005010/segment_defs/DTM.rb). There you can see the first element is [`E374`](https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/versions/005010/element_defs.rb#L995), which does show "091" as an allowed value. Perhaps you are using 003010 then, which has [this definition](https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/versions/003010/element_defs.rb#L4163-L4176)?

**Comment by kputnam** [comment]
Closing due to lack of response. Feel free to re-open if you can provide additional input
