### ISSUE TITLE
835 - 005010X221A1 - NTE segment error

### ISSUE THREAD

**Issue by chasestory** [kputnam/stupidedi#262]
I am trying to add a NTE segment to provide more information in a denial. But the error I get

"segment NTE cannot occur here at file"
 NTE segments are allowed in the spec. Not sure if I can add this to be accepted by the builder?

**Comment by chasestory** [comment]
I have tried to open up a PR but i cannot. I get permission errors.

**Comment by chasestory** [comment]
I opened a PR for this.

**Comment by kputnam** [comment]
I am closing this as NTE is not part of the standard, as mentioned on the PR. Let me know if you have problems creating your own customized 835 grammar.
