### ISSUE TITLE
File permissions issue on v1.4.3

### ISSUE THREAD

**Issue by acimadamore** [kputnam/stupidedi#272]
I'm having issues running the latest release(1.4.3) in a Docker container:
```
LoadError: cannot load such file -- /usr/local/bundle/ruby/3.2.0/gems/stupidedi-1.4.3/lib/stupidedi.rb
```
It seems to be a permissions problem in the `lib/stupidedi.rb` file:
```
$ ls -l /usr/local/bundle/ruby/3.2.0/gems/stupidedi-1.4.3/lib/stupidedi.rb
-rw------- 1 root root 1724 Jan 15 03:55 /usr/local/bundle/ruby/3.2.0/gems/...
```
I ran my application in a Docker container that does not use the root user for security reasons. 

This is not an issue in 1.4.2, also if i install the gem using the GitHub repository and the ref `v1.4.3` the files have the correct permission.

**Comment by smathy** [comment]
I confirmed this by pulling the actual gem:

```
~/work/gems gem fetch stupidedi                                                                                                                                                                          8:11:56
Fetching stupidedi-1.4.3.gem
Downloaded stupidedi-1.4.3
~/work/gems tar xzf stupidedi-1.4.3.gem                                                                                                                                                                  8:12:13
~/work/gems tar tvzf data.tar.gz lib/stupidedi.rb                                                                                                                                                        8:12:26
-rw-------  0 wheel  wheel    1724 Sep 13  2023 lib/stupidedi.rb
```

**Comment by kputnam** [comment]
Thanks for pointing this out. I will look at it today.

**Comment by kputnam** [comment]
I pushed v1.4.5, which should have the correct permissions. Let me know if you still have problems, and thank you for pointing this out. I realized I should be running `gem build` with the `--strict` flag, which will abort instead of only printing warnings.

**Comment by smathy** [comment]
Thanks

**Comment by smathy** [comment]
Hey @kputnam, I'm not actually seeing 1.4.5 on rubygems. Did you forget to `gem push` maybe?

**Comment by smathy** [comment]
Also, looks like you didn't merge 1.4.5 into `master` in GH, it's on a floating tag.

**Comment by kputnam** [comment]
Oops, you are right. I just pushed it now.

**Comment by smathy** [comment]
Disco, thanks again!

**Comment by Petercopter** [comment]
Sorry, offtopic here, hi @smathy! Small world, glad to see you! 🤗
