### ISSUE TITLE
including gem causes infinite deprecation warnings

### ISSUE THREAD

**Issue by limratana** [kputnam/stupidedi#62]
I find that including this as a gem causes the following error over and over on tests:

    Passing options to #find is deprecated. Please build a scope and then call #find on it.

If I do require: false, then no problems, unless I require the library in a test.

**Comment by limratana** [comment]
I narrowed it down and submitted a pull request undoing the change which breaks my tests : https://github.com/kputnam/stupidedi/pull/63

Admittedly, I do not fully understand why this library appears in this gem nor what kind of impact the change has.

**Comment by kputnam** [comment]
I believe this is fixed by #72. Let me know if you're still able to reproduce it.
