### ISSUE TITLE
hash.present? conflict between rails 4.2.4 and tins 1.x

### ISSUE THREAD

**Issue by serixscorpio** [kputnam/stupidedi#67]
Recently when I attempted to upgrade to use rails 4.2.4, along with stupidedi, I came across a method definition conflict.
stupidedi depends on term-ansicolor, which depends on tins.  Tins add `present?` method to Hash.
rails 4.2.4 also add `present?` method to Hash in its [active support core extensions](http://guides.rubyonrails.org/active_support_core_extensions.html).
The semantics of the above two methods are different.
Does stupidedi depend on term-ansicolor only because of being able to color the terminal output?  If so, is there some way I can turn it off and remove that dependency? or other suggestions?  Thanks.

**Comment by serixscorpio** [comment]
Actually, an update here.  It seems stupidedi uses `present?` widely as an internal interface (perhaps?)  See `lib/ruby/blank.rb`
```ruby
class Object
  def present?
    true
  end
end
```
This conflicts with rails `present?`.

**Comment by kputnam** [comment]
Sorry for the slow response. Yes, you can simply remove the dependency on term-ansicolor and the terminal output will be ordinary black-and-white.

However, you are correct that `present?` is regrettably defined by monkey-patching the `Object` class. This method and a few others are all defined in `lib/ruby`.

There was a proposal in the comments of #48 to use Ruby's refinements to limit the scope of these patches, but I don't think anyone is working on it. I don't really have the time to work on that nor test that it fixes the interaction with Rails, but would gladly accept a pull request. This issue has affected many people, and is a big regret!

**Comment by kputnam** [comment]
Fixed by #72
