### ISSUE TITLE
Leverage ruby 2.3.0 frozen string literal pragma?

### ISSUE THREAD

**Issue by irobayna** [kputnam/stupidedi#73]
@kputnam Now that ```ruby 2.3.0 ``` has been released I am wondering if we should try experimenting with the new ```frozen string literal pragma```?  In theory sounds like ```stupidedi``` could benefit from it, i.e: less memory usage and faster processing.  Thoughts?

**Comment by irobayna** [comment]
@kputnam I have created a new branch ```inmmutable_string``` with the needed changes to support immutable strings (add magic comment line to each file ```# frozen_string_literal: true```) in preparation for ```ruby 3.0``` which will have this behavior by default.  All specs run now and I am about to exercise this code with some real transactions.  

Can you think of anyone I can ping to help exercise this code?

**Comment by kputnam** [comment]
You might look at places where we use `<<` to find other potential issues:

```
$ grep -R '" <<' lib/stupidedi
$ grep -R '<< "' lib/stupidedi
```

**Comment by irobayna** [comment]
@kputnam done! 

Specs run OK

```845 examples, 0 failures, 12 pending```

I wonder if by having frozen strings we will see less memory consumption and perhaps a performance boost.

**Comment by kputnam** [comment]
Not sure if you're waiting for me, but feel free to merge it!

**Comment by irobayna** [comment]
Ok. I will :-)
