### ISSUE TITLE
Floating Fields?

### ISSUE THREAD

**Issue by irobayna** [kputnam/stupidedi#74]
@kputnam Did you ever heard of ```Usage:``` ```Floating```?

I have come across a more accurate specs for one of the messages I implemented and realized a segment I struggle with happens to be ```Floating```.  

It appears floating means that it can appear anywhere.  Any thoughts on how to handle this?

**Comment by irobayna** [comment]
It appears ```Floating``` fields are discouraged, so never mind. closing this.

```F``` Floating 

> This item may appear at any point within a transaction set - now
disallowed for insertion into any existing or new transaction sets, and
discouraged for use or implementation in older transaction sets.

**Comment by kputnam** [comment]
Nope, I haven't heard of it but I'm glad it's discouraged. I have no idea how we would address those :-)
