### ISSUE TITLE
"can't modify frozen String" from float_val.rb while generating 837 output

### ISSUE THREAD

**Issue by PetriWessman** [kputnam/stupidedi#82]
Using ruby 2.3.1 and latest stupidedi (1.2.9), I get the following error when trying to generate 837 output. Not sure exactly which field is triggering it, but it's some numeric one based on the stack trace. The code there (in float_val.rb) does look a bit suspicious with regards to frozen strings.

>"can't modify frozen String"

>stupidedi (1.2.9) lib/stupidedi/versions/functional_groups/005010/element_types/float_val.rb:295:in `to_x12'

**Comment by kputnam** [comment]
Thanks for the report, this is fixed now in `master`. @irobayna, would you create a new release when you have time?

**Comment by irobayna** [comment]
@kputnam done!

**Comment by kputnam** [comment]
Thanks Isi!
