### ISSUE TITLE
HC837i support

### ISSUE THREAD

**Issue by pepito2k** [kputnam/stupidedi#86]
Hi,

I need to create HC837p as well as HC837i health claims.
I already have everything for the 837p, but I don't see any code for validating X223HC837P.

Is there any 'easy' way to validate that standard ?
If not, can you guide me a little bit on what should I modify/add to get it to work ? I have the standard documentation and I am willing to make the effort to add the support to the gem but It would help having a little guide on it.

Thanks,
Gonzalo.

**Comment by kputnam** [comment]
Yes! I don't think I had the "implementation guide" documentation on 837i, but if you have it, I can definitely help you encode that into something useable. I'll try to get back to you with details over the weekend.

**Comment by pepito2k** [comment]
I can send you the file with the specification if that helps you to make a quick 'how to' adapted to that file.

**Comment by kputnam** [comment]
Yes, that would help. There are a few different kinds of documentation, and I don't have any of them handy. Thanks! (Sorry I didn't have time to get back to you this weekend.)

**Comment by pepito2k** [comment]
No prob, here's a link to the file: https://dl.dropboxusercontent.com/u/14328808/x223.pdf

**Comment by kputnam** [comment]
Excellent, that's exactly what you'll need! I'll start writing up a brief guide on how to turn this into a usable definition. Probably will take a day or two.

**Comment by pepito2k** [comment]
Hey, any news on the brief guide ?

**Comment by kputnam** [comment]
Yep, I've got some notes in `doc/Transcribing.md`. Feel free to ask questions, of course.

**Comment by pepito2k** [comment]
PR opened for this: #101
