### ISSUE TITLE
Extra space on TD5 segment 

### ISSUE THREAD

**Issue by irobayna** [kputnam/stupidedi#88]
While generating a SH856, I am getting an extra space on TD5 on the second field (E66)

Example:

```TD5*B*2 *XYZZ*M````

TD5 is defined as:

```
          TD5 = s::SegmentDef.build(:TD5, "Carrier Details (Routing Sequence/Transit Time)",
            "To specify the carrier and sequence of routing and provide transit time information",
            e::E133.simple_use(r::Optional,  s::RepeatCount.bounded(1)),
            e::E66 .simple_use(r::Mandatory,  s::RepeatCount.bounded(1)),
            e::E67 .simple_use(r::Mandatory,  s::RepeatCount.bounded(1)),
            e::E91 .simple_use(r::Relational, s::RepeatCount.bounded(1)))
```
and 

E66 is defined as:

```
E66   = t::ID.new(:E66  , "Identification Code Qualifier"        , 1, 2,
            s::CodeList.build(
              "1"  => "D-U-N-S Number, Dun & Bradstreet",
              "2"  => "Standard Carrier Alpha Code (SCAC)",
...
```

Any ideas?

**Comment by kputnam** [comment]
Hmm, my first guess was `E66` might have a minimum length of 2, but that doesn't appear to be the case. I'll take a closer look.

**Comment by kputnam** [comment]
I can't reproduce this. Here's what I tried: modifying `spec/fixtures/SH856` so the GS segment is from `004010` (rather than 002001). Then I added a `TD5` segment after the `TD1` to match what you have. Lastly, I added these lines at the end of `bin/edi-pp` to print the X12:

```ruby
separators =
  Stupidedi::Reader::Separators.build(:segment => "~\n",
                                      :element => "*",
                                      :component => ":",
                                      :repetition => "^")

parser.zipper.tap do |z|
  w = Stupidedi::Writer::Default.new(z.root, separators)
  puts w.write
end
```

The output doesn't seem to have an extra space:

```
ISA*00*          *00*          *01*054481205      *01*123456789      *070101*1130*U*00400*000000001*0*P*:~
GS*SH*054481205*123456789*070101*1130*1*X*004010~
ST*856*0001~
BSN*00*35100*070101*1130~
DTM*011*070101*1130~
HL*1**S~
TD1*CNT79*3~
TD5*B*2*XYZZ*M~
```

**Comment by irobayna** [comment]
I am going to extract the logic, I am using to generate this message so you can run it on your side.  It does not make sense as I see most segments doing the right thing, yet this one does not.  I am passing the single character ```'2'``` to the value yet ```'2 '``` (2 plus a space comes out)

I started to poke around and see if I can determine where the problem is coming from.  Do you recall where  ```t::ID.new``` gets handle?

**Comment by irobayna** [comment]
I wrote a test file and it works as expected.  I believe I might have an issue with the gem version I am using, meant to use the latest but I think I might be using an older one or have two versions on the server.  Will investigate.  

Thanks for your help!

**Comment by kputnam** [comment]
Ah, that might be the cause. You can try inspecting the `E66` object at runtime, I think it might include min/max lengths in the output of `p`... if you see the min length is 2, that would explain it. To answer your question, `ID.new` is in `element_types/identifier_val.rb` (for whichever version of X12), and `ID` is an alias for the `IdentifierVal` class.
