### ISSUE TITLE
Have closing entries generate their own counts

### ISSUE THREAD

**Issue by gisborne** [kputnam/stupidedi#89]
It is awkward, inconvenient and surely unnecessary for me to have to keep track of the number of lines in the ST segment.

Is there a way to get the count? Even better, can I just do b.SE and have it fill in the details?

Actually, the Rubyish way would be a block:

b.ST do
…
end

**Comment by kputnam** [comment]
Please see https://github.com/kputnam/stupidedi/issues/53
