### ISSUE TITLE
Error running statements from irb w/ ruby 2.3

### ISSUE THREAD

**Issue by mlos100** [kputnam/stupidedi#92]
While trying to enter statements from edi-pp into irb with Ruby 2.3. 1, I encountered an error, Can't modify frozen string.  I was using Ubuntu; a colleague, who confirmed the issue occurred for him also, was on a Mac.

I've attached a screen shot that depicts the statements we executed.

<img width="983" alt="screen shot 2016-07-28 at 10 49 16 am" src="https://cloud.githubusercontent.com/assets/3521448/17253108/485648cc-557d-11e6-97d5-c7590075ecca.png">

**Comment by irobayna** [comment]
@mlos100 Try the latest version v.1.2.12,  pull request #[91] fix this issue

**Comment by mlos100** [comment]
Thanks!  I'm working in irb to try to get familiar with the different structures.
