### ISSUE TITLE
m.distance (between) thrown into endless loop

### ISSUE THREAD

**Issue by tamagokun** [kputnam/stupidedi#95]
I am trying to calculate the number of segments between the current position in the builder and the previous ST segment. I've seen #53 and the methods used there. However, it is getting into an endless loop.

Here's the snippet for some context:

```ruby
m = b.machine

st = m
while st.segment.fetch.node.id != :ST
  st = st.parent.fetch
end

count = 1 + m.distance(st)
```

I've managed to track down the issue to this loop (https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/zipper/abstract_cursor.rb#L110-L113)

It seems like once it gets into that loop, `zipper1` isn't getting re-assigned, so I updated that loop to:

```ruby
until zipper1.last?
  zipper1 = zipper1.next
  between.concat(zipper1.flatten)
end
```

That seemed to do it! I thought I was all set, but i've noticed that i'm getting incorrect numbers depending on the number of transactions. So, the first ST/SE set will get the correct count, but the second ST/SE set will be one greater than the correct count. I'm really not keen on the `between` method to know what might be throwing the numbers askew.

**Comment by tamagokun** [comment]
Ah ha! Actually, this change worked. I was manually calling between on the two cursors rather than fixing it to use `m.distance` which was causing the issue.

If you would like a pull request to fix that loop, I can do that!

**Comment by kputnam** [comment]
Yes, I've run into this but couldn't reproduce it. I'll gladly accept a PR to fix it, your proposed change looks correct to me.
