### ISSUE TITLE
stupidedi / Issues on Parsing HC 837 file 

### ISSUE THREAD

**Issue by pradoshac** [kputnam/stupidedi#99]
require "stupidedi"

config = Stupidedi::Config.hipaa
parser = Stupidedi::Builder::StateMachine.build(config)

input  = File.open('D:/stupidedi/myfile.txt' )
        

# Reader.build accepts IO (File), String, and DelegateInput
parser,result = parser.read(Stupidedi::Reader.build(input))

# Report fatal tokenizer failures

if result.fatal?

  result.explain{|reason| raise reason + " at #{result.position.inspect}" }
end

def el(m, *ns, &block)
 

  if Stupidedi::Either === m
  
 
    m.tap{|m| el(m, *ns, &block) }
  else
   
    yield(*ns.map{|n| m.element(*n).map(&:node).map(&:value).fetch(nil) })
  end
end

# Print some information
parser.first
  .flatmap{|m| m.find(:GS) }
  .flatmap{|m| m.find(:ST) }
  .tap do |m|
    el(m.find(:N1, "PR"), 2){|e| puts "Payer: #{e}" }
   
end

Iam a beginer with ruby and stupidedi.I need to parse an HC837 file by using stupidedi.I used the above code for reading and traversing my HC 837 edi file.. but does not show the resulting payer information.And also there is no error.But in the case of HP835 file it is working. Is it need any modification for parsing HC837  file by the above code..please give me an idea of parsing HC837 file..

thanks,
praad

**Comment by pradoshac** [comment]
a section from MY input HC837 file is below..
ISA*00*          *00*          *ZZ*CIRIUS         *ZZ*WH             *150113*1345*^*00501*109201135*0*P*>~
GS*HC*CIRIUS*WH*20150113*1345*109201135*X*005010X223A2~
ST*837*000092*005010X223A2~
BHT*0019*00*MIRUS092 I-01132015*20150113*1345*CH~
NM1*41*2*WESTLAND HOUSE*****46*WH~
PER*IC*CIRIUS SUPPORT*TE*9256859300*FX*9256856526~
NM1*40*2*WH*****46*WH~
HL*1**20*1~
PRV*BI*PXC*314000000X~
NM1*85*2*WESTLAND HOUSE*****XX*1598754491~
N3*100 BARNET SEGAL LANE~
N4*MONTEREY*CA*939407000~
REF*EI*940760193~
NM1*87*2~
N3*DEPT 33290 PO BOX 39000~
N4*SAN FRANCISCO*CA*94139~
HL*2*1*22*0~
SBR*S*18*******MA~
NM1*IL*1*GILHULY*JEAN****MI*547385067A~
N3*ESTATE OF J. GILHULY*1500 MARK THOMAS DR~
N4*MONTEREY*CA*93940~
DMG*D8*19310313*F~
NM1*PR*2*MEDICARE*****PI*01011~
N3*PO BOX 971~
N4*AUGUSTA*GA*30903~
CLM*260086194-14*11981.14***21>A>2**A*Y*Y~
DTP*434*RD8*20141026-20141031~
DTP*435*DT*201410261500~
CL1*3*4*30~
REF*EA*918506~

**Comment by kputnam** [comment]
I'm not sure I can diagnose the problem from what you've described. Does it print anything at all from the 837 file, or is it only missing the payer information? Two tools you can use to be sure the file is valid in in `bin/edi-pp` and `bin/edi-ed`, which should print information to the console.

It could be the file you provided simply doesn't have any information that matches what you're looking for (`N1*PR`). There are also some sample 837 files in the `spec/fixtures` directory that you could use for comparison to help troubleshoot.
